Ashwani forking. Just a test for forking.
pradipta/pradipta.github.io pull request #3
Opened 2020-12-03 08:41 UTC by AV-013

2020-12-03 08:43 UTC, pradipta requested changes
Lol

2020-12-03 10:14 UTC, AV-013 commented
> Lol.
> In the latest blog there's a line: `To use the same with a Java, you would need the following dependencies (in addition to the Mongo Java Driver/Spring Mongo data that you’d use to set up the application anyways):`. Change it to `To use the same with Java.....`. Remove the `a`

I dont think i can edit your blog ?

2020-12-03 12:45 UTC, AV-013 commented
check this

2020-12-03 17:29 UTC, pradipta requested changes

2020-12-03 17:29 UTC, pradipta commented on README.md
> +Ashwani forking example. Just a test .......
Revert this change

2020-12-04 05:44 UTC, pradipta approved these changes

2020-12-04 05:44 UTC, merged